FROM alpine:3.21 AS builder

ARG KERNEL_VERSION=6.12.91

RUN apk add --no-cache \
    build-base bc bison flex elfutils-dev perl \
    linux-headers diffutils findutils

RUN wget -q "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz" \
    && tar xf "linux-${KERNEL_VERSION}.tar.xz" \
    && rm "linux-${KERNEL_VERSION}.tar.xz"

WORKDIR /linux-${KERNEL_VERSION}

# Start from x86_64 defconfig, then apply Dew overrides
RUN make x86_64_defconfig

# Dew VM monolithic config: all containerd features built-in, no modules
COPY config-dew-virt-x86_64.fragment /tmp/
RUN cat /tmp/config-dew-virt-x86_64.fragment >> .config \
    && make olddefconfig \
    && make -j"$(nproc)" bzImage \
    && cp arch/x86/boot/bzImage /vmlinuz-dew-virt

FROM scratch
COPY --from=builder /vmlinuz-dew-virt /vmlinuz-dew-virt
