//go:build ignore

// gen_syscallgroups.go regenerates syscallgroups.go from systemd's
// src/shared/seccomp-util.c. It mirrors the @-group → syscall-name tables a
// pinned systemd release ships, so dew can expand SystemCallFilter=@group
// directives (5c) the same way systemd does.
//
// Usage:
//
//	go generate ./internal/confine/      # fetches the pinned release over HTTP
//	go run gen_syscallgroups.go path.c   # parse a local seccomp-util.c instead
//
// The emitted table is the cross-arch *union* of each group's members (the C
// source guards some names per-arch with #if, which this parser ignores). The
// guest agent drops names absent from its own arch table when assembling the
// BPF, recovering each architecture's exact subset — see cmd/dew-agent/seccomp.go.
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

// systemdVersion is the pinned release we mirror. Bump it deliberately and
// re-run go generate; record the bump in the commit message and CHANGELOG.
const systemdVersion = "v257"

const sourceURL = "https://raw.githubusercontent.com/systemd/systemd/" + systemdVersion + "/src/shared/seccomp-util.c"

var (
	nameRe = regexp.MustCompile(`\.name = "(@[a-z0-9-]+)"`)
	litRe  = regexp.MustCompile(`"([^"]*)"`)
)

func main() {
	src, err := load()
	if err != nil {
		fmt.Fprintln(os.Stderr, "load:", err)
		os.Exit(1)
	}
	raw := parse(src)
	delete(raw, "@known") // depends on a generated syscall-list.h; not resolvable here

	resolved := map[string][]string{}
	missing := map[string]bool{}
	for g := range raw {
		set := map[string]bool{}
		for _, n := range resolve(g, raw, map[string]bool{}, missing) {
			set[n] = true
		}
		names := make([]string, 0, len(set))
		for n := range set {
			names = append(names, n)
		}
		sort.Strings(names)
		resolved[g] = names
	}
	// Fail loudly rather than emit a silently incomplete table: a referenced
	// @-group absent from the source means the parser missed it or systemd added
	// a new group. (@known is intentionally skipped, never recursed into.)
	if len(missing) > 0 {
		refs := make([]string, 0, len(missing))
		for r := range missing {
			refs = append(refs, r)
		}
		sort.Strings(refs)
		fmt.Fprintf(os.Stderr, "unresolved @-group references: %s\n", strings.Join(refs, ", "))
		os.Exit(1)
	}

	if err := emit(resolved); err != nil {
		fmt.Fprintln(os.Stderr, "emit:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote syscallgroups.go: %d groups from systemd %s\n", len(resolved), systemdVersion)
}

// load returns the seccomp-util.c source, from a local path arg or the pinned URL.
func load() (string, error) {
	if len(os.Args) > 1 {
		b, err := os.ReadFile(os.Args[1])
		return string(b), err
	}
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(sourceURL)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("GET %s: %s", sourceURL, resp.Status)
	}
	b, err := io.ReadAll(resp.Body)
	return string(b), err
}

// parse extracts each set's raw token list (tokens may be @group references).
func parse(src string) map[string][]string {
	groups := map[string][]string{}
	cur := ""
	capturing := false
	for _, ln := range strings.Split(src, "\n") {
		if m := nameRe.FindStringSubmatch(ln); m != nil {
			cur, capturing = m[1], false
			continue
		}
		if cur == "" {
			continue
		}
		if strings.Contains(ln, ".value =") {
			capturing = true
			continue
		}
		if !capturing {
			continue
		}
		if strings.Contains(ln, "},") || strings.Contains(ln, ".help") || strings.Contains(ln, ".name") {
			cur, capturing = "", false
			continue
		}
		for _, m := range litRe.FindAllStringSubmatch(ln, -1) {
			for _, tok := range strings.Split(m[1], `\0`) {
				if tok = strings.TrimSpace(tok); tok != "" {
					groups[cur] = append(groups[cur], tok)
				}
			}
		}
	}
	return groups
}

// resolve expands @group references transitively (cycle-safe), returning only
// plain syscall names.
func resolve(g string, raw map[string][]string, seen, missing map[string]bool) []string {
	if seen[g] {
		return nil
	}
	seen[g] = true
	var out []string
	for _, tok := range raw[g] {
		if strings.HasPrefix(tok, "@") {
			if tok == "@known" {
				continue
			}
			if _, ok := raw[tok]; !ok {
				missing[tok] = true
				continue
			}
			out = append(out, resolve(tok, raw, seen, missing)...)
			continue
		}
		out = append(out, tok)
	}
	return out
}

func emit(resolved map[string][]string) error {
	gnames := make([]string, 0, len(resolved))
	for g := range resolved {
		gnames = append(gnames, g)
	}
	sort.Strings(gnames)

	var b strings.Builder
	b.WriteString("// Code generated by gen_syscallgroups.go; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: systemd %s src/shared/seccomp-util.c\n", systemdVersion)
	fmt.Fprintf(&b, "// Regenerate with: go generate ./internal/confine/\n\n")
	b.WriteString("package confine\n\n")
	fmt.Fprintf(&b, "// systemdVersion is the systemd release whose @-group tables this mirrors.\n")
	fmt.Fprintf(&b, "const systemdVersion = %q\n\n", systemdVersion)
	b.WriteString("// systemdSyscallGroups maps a systemd SystemCallFilter= @-group to the\n")
	b.WriteString("// cross-arch union of its syscall names (references to other groups already\n")
	b.WriteString("// expanded). The guest agent drops names absent from its arch when building\n")
	b.WriteString("// the BPF, so each architecture gets its correct subset.\n")
	b.WriteString("var systemdSyscallGroups = map[string][]string{\n")
	for _, g := range gnames {
		fmt.Fprintf(&b, "\t%q: {", g)
		for i, n := range resolved[g] {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", n)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	return os.WriteFile("syscallgroups.go", []byte(b.String()), 0o644)
}
