#!/usr/bin/env bash
# gen-asset-shas.sh — generate cmd/dew/assets_shas_generated.go from a
# sha256sum manifest, baking the SHA256 of every release asset dew
# downloads at runtime into the binary. dew then content-addresses its
# asset cache (<name>.<sha8>) so a stale/corrupt cached kernel or
# initramfs from a previous version is structurally impossible to reuse.
#
# Usage: gen-asset-shas.sh <manifest> <out.go>
#   <manifest>: `sha256sum` output — "<sha>  <filename>" per line.
#   <out.go>:   destination, normally cmd/dew/assets_shas_generated.go
#
# Used by BOTH the build-macos job (before it compiles the darwin
# binaries) and the goreleaser job (before it compiles the linux ones),
# so every published binary embeds the SHAs — previously only the linux
# binaries did, leaving darwin with an empty map and reusing stale
# cached assets across upgrades.
set -euo pipefail

MANIFEST="${1:?usage: gen-asset-shas.sh <manifest> <out.go>}"
OUT="${2:?usage: gen-asset-shas.sh <manifest> <out.go>}"

if [ ! -f "$MANIFEST" ]; then
	echo "::error::asset SHA manifest not found: $MANIFEST" >&2
	exit 1
fi

{
	echo '// Code generated by scripts/gen-asset-shas.sh — DO NOT EDIT.'
	echo "// Source: $(basename "$MANIFEST")"
	echo 'package main'
	echo ''
	echo 'func init() {'
	# "sha  filename" → ExpectedAssetSHA["filename"] = "sha".
	# Plain string concatenation (POSIX awk, not gawk-only %q) so this
	# also runs under BSD awk for local dev. Asset filenames are
	# alphanumeric + dashes + dots and sha256sums are pure hex, so no
	# escaping is needed.
	awk '{ print "\tExpectedAssetSHA[\"" $2 "\"] = \"" $1 "\"" }' "$MANIFEST"
	echo '}'
} >"$OUT"

echo "── $OUT ──"
cat "$OUT"
